function DM=DERIV1(NT,NF,XLIQ,YVAP,VB,F,R)
% DERIV1.M
% PERSAMAAN DERIVATIF YANG DIPAKAI DALAM PENYELESAIAN
%
% PERSAMAAN DERIVATIF HOLDUP LIQUID TOTAL PADA TIAP TRAY
N=1;
DM(N)=XLIQ(N+1)+VB-XLIQ(N)-YVAP(N);
for N=2:NF-1;
   DM(N)=XLIQ(N+1)+YVAP(N-1)-XLIQ(N)-YVAP(N);
end
N=NF;
DM(N)=XLIQ(N+1)+F+YVAP(N-1)-XLIQ(N)-YVAP(N);
for N=NF+1:NT-1
    DM(N)=XLIQ(N+1)+YVAP(N-1)-XLIQ(N)-YVAP(N);
end
%
N=NT;
DM(N)=R+YVAP(N-1)-XLIQ(N)-YVAP(N);
return